const AUTH_SUCCESS = 'AUTH_SUCCESS'
const AUTH_LOGOUT = 'AUTH_LOGOUT'
const AUTH_LOADING = 'AUTH_LOADING'
const AUTH_ERROR = 'AUTH_ERROR'
const ON_PAGE_LOADED = 'ON_PAGE_LOADED'

export {
	AUTH_SUCCESS,
	AUTH_LOGOUT,
	AUTH_LOADING,
	AUTH_ERROR,
	ON_PAGE_LOADED
}